# .github/workflows/ci-cd.yml
name: CI/CD - Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  # ========================================
  # FRONTEND BUILD & DEPLOY
  # ========================================
  frontend:
    name: Frontend - Build & Deploy
    runs-on: ubuntu-latest
    environment: Prod
    
    strategy:
      matrix:
        app:
          - name: ayudantes
            path: front-end/ayudantes
            image_name: asistencias-qr
          - name: estudiantes
            path: front-end/estudiantes
            image_name: estudiantes-qr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Cache dependencies
    - name: Cache node modules for ${{ matrix.app.name }}
      uses: actions/cache@v4
      with:
        path: ${{ matrix.app.path }}/node_modules
        key: ${{ runner.os }}-${{ matrix.app.name }}-${{ hashFiles(format('{0}/package-lock.json', matrix.app.path)) }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.app.name }}-

    # Install and build
    - name: Install dependencies for ${{ matrix.app.name }}
      working-directory: ${{ matrix.app.path }}
      run: npm ci || npm install

    - name: Build ${{ matrix.app.name }} static files
      working-directory: ${{ matrix.app.path }}
      run: |
        npx expo install --fix
        npx expo export -p web --output-dir dist

    # Extract metadata for Docker
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.app.image_name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    # Build and push Docker image
    - name: Build and push ${{ matrix.app.name }} Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.app.path }}
        file: ${{ matrix.app.path }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha,scope=${{ matrix.app.name }}
        cache-to: type=gha,mode=max,scope=${{ matrix.app.name }}

    - name: Generate build summary
      if: github.event_name != 'pull_request'
      run: |
        echo "## 🎨 Frontend Built: ${{ matrix.app.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **App**: ${{ matrix.app.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: \`${{ env.DOCKERHUB_USERNAME }}/${{ matrix.app.image_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags**: \`${{ steps.meta.outputs.tags }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

  # ========================================
  # BACKEND BUILD & DEPLOY
  # ========================================
  backend:
    name: Backend - Build & Deploy
    runs-on: ubuntu-latest
    environment: Prod
    
    strategy:
      matrix:
        service:
          - name: api-estudiantes
            context: back-end/api_estudiantes
            dockerfile: back-end/api_estudiantes/Dockerfile
            image_name: acceso-api-estudiantes
          - name: lector-qr
            context: back-end/lector
            dockerfile: back-end/lector/Dockerfile
            image_name: acceso-lector-qr
          - name: web-api
            context: back-end/web
            dockerfile: back-end/web/Dockerfile
            image_name: acceso-web-api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Extract metadata for Docker
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service.image_name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    # Auto-create optimized Dockerfile if missing
    - name: Ensure Dockerfile exists
      run: |
        if [ ! -f "${{ matrix.service.dockerfile }}" ]; then
          echo "🔧 Creating optimized Dockerfile for ${{ matrix.service.name }}"
          mkdir -p $(dirname "${{ matrix.service.dockerfile }}")
          
          case "${{ matrix.service.name }}" in
            "api-estudiantes"|"web-api")
              cat > "${{ matrix.service.dockerfile }}" << 'EOF'
        FROM python:3.11-slim
        
        # Metadatos
        LABEL maintainer="acceso.informaticauaint.com"
        LABEL description="${{ matrix.service.name }} para sistema de acceso"
        
        # Variables de entorno
        ENV PYTHONDONTWRITEBYTECODE=1 \
            PYTHONUNBUFFERED=1 \
            FLASK_APP=app.py \
            FLASK_ENV=production \
            PIP_NO_CACHE_DIR=1 \
            PIP_DISABLE_PIP_VERSION_CHECK=1
        
        # Instalar dependencias del sistema en una sola capa
        RUN apt-get update && apt-get install -y --no-install-recommends \
            gcc \
            curl \
            && rm -rf /var/lib/apt/lists/* \
            && apt-get clean
        
        # Crear usuario no-root
        RUN groupadd -r appuser && useradd -r -g appuser appuser
        
        # Crear directorio de trabajo
        WORKDIR /app
        
        # Copiar y instalar dependencias (aprovechar cache de Docker)
        COPY requirements.txt .
        RUN pip install --no-cache-dir --upgrade pip && \
            pip install --no-cache-dir -r requirements.txt
        
        # Copiar código fuente
        COPY . .
        
        # Cambiar propietario de archivos
        RUN chown -R appuser:appuser /app
        
        # Cambiar a usuario no-root
        USER appuser
        
        # Exponer puerto
        EXPOSE 5000
        
        # Health check optimizado
        HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
            CMD curl -f http://localhost:5000/api/health || exit 1
        
        # Comando por defecto optimizado
        CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--threads", "2", "--timeout", "60", "--keep-alive", "2", "app:app"]
        EOF
              ;;
            "lector-qr")
              cat > "${{ matrix.service.dockerfile }}" << 'EOF'
        FROM python:3.11-slim
        
        # Metadatos
        LABEL maintainer="acceso.informaticauaint.com"
        LABEL description="Lector QR para sistema de acceso"
        
        # Variables de entorno
        ENV PYTHONDONTWRITEBYTECODE=1 \
            PYTHONUNBUFFERED=1 \
            PIP_NO_CACHE_DIR=1 \
            PIP_DISABLE_PIP_VERSION_CHECK=1
        
        # Instalar dependencias del sistema para QR
        RUN apt-get update && apt-get install -y --no-install-recommends \
            gcc \
            curl \
            libzbar0 \
            libzbar-dev \
            && rm -rf /var/lib/apt/lists/* \
            && apt-get clean
        
        # Crear usuario no-root
        RUN groupadd -r appuser && useradd -r -g appuser appuser
        
        # Crear directorio de trabajo
        WORKDIR /app
        
        # Copiar y instalar dependencias
        COPY requirements.txt .
        RUN pip install --no-cache-dir --upgrade pip && \
            pip install --no-cache-dir -r requirements.txt
        
        # Copiar código fuente
        COPY . .
        
        # Cambiar propietario de archivos
        RUN chown -R appuser:appuser /app
        
        # Cambiar a usuario no-root
        USER appuser
        
        # Exponer puerto
        EXPOSE 8000
        
        # Health check básico
        HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
            CMD curl -f http://localhost:8000/health || exit 1
        
        # Comando por defecto
        CMD ["python", "app.py"]
        EOF
              ;;
          esac
        else
          echo "✅ Dockerfile already exists for ${{ matrix.service.name }}"
        fi

    # Build and push Docker image
    - name: Build and push ${{ matrix.service.name }} Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha,scope=${{ matrix.service.name }}
        cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}

    - name: Generate build summary
      if: github.event_name != 'pull_request'
      run: |
        echo "## ⚙️ Backend Built: ${{ matrix.service.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Service**: ${{ matrix.service.name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: \`${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service.image_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags**: \`${{ steps.meta.outputs.tags }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

  # ========================================
  # SECURITY SCAN (Solo en main/master)
  # ========================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment: Prod
    
    strategy:
      fail-fast: false  # Continuar aunque falle un scan
      matrix:
        image:
          - asistencias-qr
          - estudiantes-qr
          - acceso-api-estudiantes
          - acceso-lector-qr
          - acceso-web-api

    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest'
        format: 'sarif'
        output: 'trivy-results-${{ matrix.image }}.sarif'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'  # No fallar el workflow por vulnerabilidades

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results-${{ matrix.image }}.sarif'

    - name: Generate security summary
      if: always()
      run: |
        echo "## 🔍 Security Scan: ${{ matrix.image }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: \`${{ env.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Scanner**: Trivy (CRITICAL,HIGH)" >> $GITHUB_STEP_SUMMARY
        echo "- **Results**: Uploaded to Security tab" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

  # ========================================
  # NOTIFICACIÓN Y DEPLOYMENT CONSOLIDADO
  # ========================================
  deploy-and-notify:
    name: Deploy & Notify Server
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    environment: Prod

    steps:
    - name: Generate webhook payload
      id: payload
      run: |
        # Crear payload simple como el que funciona manualmente
        TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        PAYLOAD='{"ref":"${{ github.ref }}","repository":"${{ github.repository }}","commit":"${{ github.sha }}","pusher":"${{ github.actor }}","timestamp":"'$TIMESTAMP'"}'
        
        # Guardar payload usando multiline output
        {
          echo "payload<<EOF"
          echo "$PAYLOAD"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        echo "📦 Payload generado: $PAYLOAD"

    - name: Generate signature
      id: signature
      run: |
        # Generar firma exactamente como funciona manualmente
        SIGNATURE=$(echo -n '${{ steps.payload.outputs.payload }}' | openssl dgst -sha256 -hmac '${{ secrets.WEBHOOK_SECRET }}' | cut -d' ' -f2)
        
        echo "🔐 Firma generada: sha256=$SIGNATURE"
        echo "signature=sha256=$SIGNATURE" >> $GITHUB_OUTPUT

    - name: Trigger server update
      id: webhook
      run: |
        echo "🚀 Enviando webhook al servidor..."
        echo "🔐 Firma: ${{ steps.signature.outputs.signature }}"
        echo "📦 Payload: ${{ steps.payload.outputs.payload }}"
        echo ""
        
        # Enviar webhook usando URL hardcodeada (como el manual que funciona)
        RESPONSE=$(curl -s -w "%{http_code}" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: ${{ steps.signature.outputs.signature }}" \
          -d '${{ steps.payload.outputs.payload }}' \
          "https://acceso.informaticauaint.com/webhook/docker-update")
        
        # Procesar respuesta
        HTTP_CODE="${RESPONSE: -3}"
        BODY="${RESPONSE%???}"
        
        echo "📊 Código de respuesta: $HTTP_CODE"
        echo "📝 Respuesta del servidor: $BODY"
        
        # Evaluar resultado
        if [ "$HTTP_CODE" -eq 200 ]; then
          echo "✅ Webhook enviado exitosamente"
          echo "webhook_status=success" >> $GITHUB_OUTPUT
        else
          echo "❌ Error enviando webhook (HTTP $HTTP_CODE)"
          echo "webhook_status=error" >> $GITHUB_OUTPUT
          echo "🔍 Response body: $BODY"
          exit 1
        fi

    - name: Verify server health
      if: steps.webhook.outputs.webhook_status == 'success'
      run: |
        echo "🔍 Verificando salud del servidor..."
        
        # Esperar un poco para que el servidor procese
        sleep 5
        
        # Verificar health check
        HEALTH_RESPONSE=$(curl -s "https://acceso.informaticauaint.com/webhook/health" || echo "ERROR")
        
        if echo "$HEALTH_RESPONSE" | grep -q "healthy"; then
          echo "✅ Servidor respondiendo correctamente"
          echo "🎯 Servidor procesando actualización..."
        else
          echo "⚠️  Servidor no responde al health check"
          echo "🔍 Respuesta: $HEALTH_RESPONSE"
        fi

    - name: Generate deployment summary
      if: always()
      run: |
        # Determinar estado del deployment
        WEBHOOK_STATUS="${{ steps.webhook.outputs.webhook_status }}"
        
        echo "# 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "$WEBHOOK_STATUS" = "success" ]; then
          echo "## ✅ Deployment Successful" >> $GITHUB_STEP_SUMMARY
        elif [ "$WEBHOOK_STATUS" = "timeout" ]; then
          echo "## ⏰ Deployment Timeout" >> $GITHUB_STEP_SUMMARY
        else
          echo "## ❌ Deployment Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🎨 Frontend Applications:" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.DOCKERHUB_USERNAME }}/asistencias-qr:latest\` - Aplicación para Ayudantes" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.DOCKERHUB_USERNAME }}/estudiantes-qr:latest\` - Aplicación para Estudiantes" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ⚙️ Backend Services:" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.DOCKERHUB_USERNAME }}/acceso-api-estudiantes:latest\` - API de Estudiantes" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.DOCKERHUB_USERNAME }}/acceso-lector-qr:latest\` - Servicio Lector QR" >> $GITHUB_STEP_SUMMARY
        echo "- \`${{ env.DOCKERHUB_USERNAME }}/acceso-web-api:latest\` - API Web Principal" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Build Information:" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Pusher**: \`${{ github.actor }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Workflow Run**: \`${{ github.run_id }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "$WEBHOOK_STATUS" = "success" ]; then
          echo "### 🔗 Server Status:" >> $GITHUB_STEP_SUMMARY
          echo "- **Webhook**: ✅ Sent successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Server**: 🔄 Processing update..." >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "_Deployment completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)_" >> $GITHUB_STEP_SUMMARY
