name: Build and Push Docker Images

on:
  push:
    branches: [ main ]  # Solo main para prod
    paths:
      - 'back-end/**'
  workflow_dispatch:  # Permitir activación manual

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: acceso.informaticauaint.com/api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod  # Environment de producción
    # Solo ejecutar en main branch para producción
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        include:
          - context: ./back-end/web
            image: web
            dockerfile: Dockerfile
          - context: ./back-end/lector
            image: lector
            dockerfile: Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify production deployment
      run: |
        echo "🚀 Desplegando a producción desde branch: ${{ github.ref }}"
        echo "🏗️ Environment: ${{ github.environment }}"
        echo "🔧 Building image: ${{ matrix.image }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify Docker Hub credentials
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "❌ DOCKERHUB_USERNAME no configurado en environment prod"
          exit 1
        fi
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "❌ DOCKERHUB_TOKEN no configurado en environment prod"
          exit 1
        fi
        echo "✅ Credentials verificados para environment prod"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}
        tags: |
          type=raw,value=latest
          type=sha,prefix=prod-
          type=raw,value={{date 'YYYYMMDD-HHmmss' tz='America/Santiago'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.context }}/${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Production deployment summary
      run: |
        echo "🎉 Imagen desplegada exitosamente:"
        echo "📦 ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}:latest"
        echo "🔗 ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}:prod-${{ github.sha }}"

  security-scan:
    runs-on: ubuntu-latest
    environment: prod
    needs: build-and-push
    strategy:
      matrix:
        image: [web, lector]
    
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.image }}:latest
        format: 'sarif'
        output: 'trivy-results-${{ matrix.image }}.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results-${{ matrix.image }}.sarif'
