name: Export Expo Web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run export:web

      - uses: actions/upload-artifact@v4
        with:
          name: expo-web
          path: front-end/dist/
