name: Export Expo Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  export-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Export web build
        run: npx expo export:web

      - name: Upload static web export
        uses: actions/upload-artifact@v3
        with:
          name: expo-web
          path: dist/
