name: Build static web files

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Set EXPO_PUBLIC env variables
      run: echo 'EXPO_PUBLIC_ENV=production' >> $GITHUB_ENV

    - name: Export Expo Web
      run: npx expo export:web

    - name: Upload web build (dist/) as artifact
      uses: actions/upload-artifact@v3
      with:
        name: expo-web-dist
        path: dist
