name: Build static web files

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Export Expo Web (modern bundler)
      run: npx expo export --platform web

    - name: Upload web build (dist/) as artifact
      uses: actions/upload-artifact@v4
      with:
        name: expo-web-dist
        path: front-end/dist
